// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEczVnse0zkrL-bNVEfaFH7wHuer24_Ls',
    appId: '1:506907711616:web:9c8c2d2ae6cd439754ae65',
    messagingSenderId: '506907711616',
    projectId: 'preserv-2ec8e',
    authDomain: 'preserv-2ec8e.firebaseapp.com',
    storageBucket: 'preserv-2ec8e.appspot.com',
    measurementId: 'G-85YZGZBFZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdvARj4XqshR1XJN7oA8Quh_KMyDziMJw',
    appId: '1:506907711616:android:f94a70fc4c5fb89854ae65',
    messagingSenderId: '506907711616',
    projectId: 'preserv-2ec8e',
    storageBucket: 'preserv-2ec8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD965ItfWXiMXOeJpONpDESfNEllY_W3Cs',
    appId: '1:506907711616:ios:b512454c491f7a4254ae65',
    messagingSenderId: '506907711616',
    projectId: 'preserv-2ec8e',
    storageBucket: 'preserv-2ec8e.appspot.com',
    iosClientId: '506907711616-m71ovfig3ecb464kgq9mugh8g3or85tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD965ItfWXiMXOeJpONpDESfNEllY_W3Cs',
    appId: '1:506907711616:ios:b512454c491f7a4254ae65',
    messagingSenderId: '506907711616',
    projectId: 'preserv-2ec8e',
    storageBucket: 'preserv-2ec8e.appspot.com',
    iosClientId: '506907711616-m71ovfig3ecb464kgq9mugh8g3or85tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
